version: '3.8'

services:
  product_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - product_db_data:/data/db

  product_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass rootpassword
    volumes: 
      - product_cache:/data    

volumes:
  product_db_data:
  product_cache:
    driver: local   